[project]
name = "sunpy-cloudcatalog"
version = "0.1.0"
description = "Fido client for SunPy to access CloudCatalog data holdings"
license = { file = "LICENSE" }
readme = "README.md"
keywords = [
    "cloud",
    "heliophysics",
    "package",
    "SunPy",
    "Fido",
    "CloudCatalog"
]

[project.urls]
Homepage = "https://github.com/heliocloud-data/sunpy-cloudcatalog"